CREATE DATABASE apiculture;
USE apiculture;
CREATE TABLE miel_darles (
id INT NOT NULL AUTO_INCREMENT,
nom VARCHAR (50) NOT NULL,
prix DECIMAL (10,2) NOT NULL,
origin VARCHAR (50) NOT NULL,
poids INT NOT NULL,
img VARCHAR (300),
PRIMARY KEY(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8